---

inherit_gem:
  rubocop-sensible: 'config/rubocop.yml'

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'test/support/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
